#!/bin/bash
#
# Unix script to run AceEvaluate
#
# by Mark Chavira
#
# Configuration: adjust the memory allocated to java below if necessary

ACEDIR=`dirname $0`
if test -f "$ACEDIR/c2d_arm"; then
  #export DYLD_LIBRARY_PATH=$ACEDIR
  OPTIONS=-Djava.awt.headless=true
else
  #export LD_LIBRARY_PATH=$ACEDIR
  OPTIONS=''
fi
java $OPTIONS -Xmx27000m -classpath "$ACEDIR/ace.jar:$ACEDIR/inflib.jar:$ACEDIR/jdom.jar" edu.ucla.belief.ace.AceEvaluate "$@"
