#!/bin/bash
#
# Unix script to convert functions to tables
#
# by Mark Chavira
#
# Configuration: adjust the memory allocated to java below if necessary

ACEDIR=`dirname $0`
if test -f "$ACEDIR/c2d_osx"; then
  export DYLD_LIBRARY_PATH=$ACEDIR
else
  export LD_LIBRARY_PATH=$ACEDIR
fi
java -Xmx1512m -classpath "$ACEDIR/ace.jar:$ACEDIR/inflib.jar:$ACEDIR/jdom.jar" mark.reason.apps.BnFilter -f mark.reason.flt.FltNoisyToTable1 "$@"
