#!/bin/bash
#
# Unix script to compute marginals for UAI 2008 evaluation
#
# by Mark Chavira
#
# Configuration: adjust the memory allocated to java below if necessary

ACEDIR=`dirname $0`
if test -f "$ACEDIR/c2d_arm"; then
  C2D=c2d_osx
  export DYLD_LIBRARY_PATH=$ACEDIR
else
  C2D=c2d_linux
  export LD_LIBRARY_PATH=$ACEDIR
fi
java -DACEC2D="$ACEDIR/$C2D" -Xmx3700m -classpath "$ACEDIR/ace.jar:$ACEDIR/inflib.jar:$ACEDIR/jdom.jar" mark.reason.apps.BnUai08 -m "$@"
